// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llkmsdpmybozspqcnjnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsa21zZHBteWJvenNwcWNuam50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDE4ODcsImV4cCI6MjA2NTM3Nzg4N30.anb0AO7SAzZ3jGQCHOOBFxUQx6Ri1tM8EZe_JdKlYvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);